In [1]:
import pandas as pd
import geopandas as gpd
import matplotlib.pyplot as plt

# Load data
fountain_gdf = gpd.read_file("fountain.geojson")

In [2]:
pd.set_option('display.max_columns', None)
#display all columns not truncated

In [3]:
fountain_gdf

,id,@id,alt_name,amenity,architect,architect:wikidata,architect:wikipedia,artist:wikidata,artist:wikipedia,artist_name,artwork_type,barrier,covered,description,drinking_water,ele,fence_type,fountain,gnis:feature_id,height,historic,image,indoor,intermittent,level,lit,loc_name,material,memorial,name,name:fr,natural,official_name,operator,playground,source,start_date,subject,subject:wikidata,subject:wikipedia,tourism,url,water,website,website:alternate,wikidata,wikipedia,geometry
0,way/260910558,way/260910558,None,fountain,None,None,None,None,None,None,None,None,None,None,None,None,None,None,None,None,None,None,None,None,None,None,None,None,None,None,None,None,None,None,None,None,None,None,None,None,None,None,None,None,None,None,None,"POLYGON ((-73.97939 40.76179, -73.97943 40.761..."
1,way/260910559,way/260910559,None,fountain,None,None,None,None,None,None,None,None,None,None,None,None,None,None,None,None,None,None,None,None,None,None,None,None,None,None,None,water,None,None,None,None,None,None,None,None,None,None,basin,None,None,None,None,"POLYGON ((-73.97966 40.76141, -73.97970 40.761..."
2,way/262576692,way/262576692,None,fountain,None,None,None,None,None,None,None,None,None,None,None,None,None,None,None,None,None,None,None,None,None,None,None,None,None,None,None,water,None,None,None,None,None,None,None,None,None,None,basin,None,None,None,None,"POLYGON ((-73.98771 40.76260, -73.98773 40.762..."
3,way/329988120,way/329988120,None,fountain,None,None,None,None,None,None,None,fence,None,None,no,None,railing,None,None,None,None,None,None,None,0,yes,None,None,None,Revson Fountain,None,None,None,None,None,None,None,None,None,None,None,None,None,https://www.nycgovparks.org/parks/M232/monumen...,None,None,None,"POLYGON ((-73.98336 40.77231, -73.98336 40.772..."
4,way/371854423,way/371854423,None,fountain,None,None,None,None,None,None,None,None,None,None,None,None,None,None,None,None,None,None,None,None,None,None,None,None,None,Reflecting Fountain,None,water,None,None,None,None,None,None,None,None,None,None,basin,None,None,None,None,"POLYGON ((-74.00988 40.70265, -74.00989 40.702..."
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
144,node/11656237160,node/11656237160,None,fountain,None,None,None,None,None,None,None,None,None,None,no,None,None,jet_water,None,None,None,None,None,None,None,yes,None,None,None,None,None,None,None,1 East River LLC,None,None,None,None,None,None,None,None,None,None,None,None,None,POINT (-73.95207 40.76660)
145,node/11656257170,node/11656257170,None,fountain,None,None,None,None,None,None,None,None,None,None,no,None,None,decorative,None,None,None,None,None,None,None,yes,None,None,None,None,None,None,None,None,None,None,None,None,None,None,None,None,None,None,None,None,None,POINT (-73.95141 40.76630)
146,node/11768058262,node/11768058262,None,fountain,None,None,None,None,None,None,None,None,None,None,no,None,None,None,None,None,None,None,None,None,None,no,None,None,None,None,None,None,None,None,None,None,None,None,None,None,None,None,None,None,None,None,None,POINT (-73.96133 40.80314)
147,node/11817550746,node/11817550746,None,fountain,None,None,None,None,None,None,None,None,None,None,no,None,None,decorative,None,None,None,None,None,None,None,no,None,None,None,None,None,None,None,None,None,None,None,None,None,None,None,None,None,None,None,None,None,POINT (-73.96821 40.80176)
148,node/11966093623,node/11966093623,None,fountain,None,None,None,None,None,None,None,None,None,Square area flush with the sidewalk with water...,no,None,None,splash_pad,None,0.5,None,None,None,None,None,None,None,None,None,None,None,None,None,None,None,None,None,None,None,None,None,None,None,None,None,None,None,POINT (-73.95938 40.81793)

In [4]:
#checking for duplicated rows
duplicate_rows = fountain_gdf[fountain_gdf.duplicated()]

#display duplicate rows
print("Duplicate Rows:")
print(duplicate_rows)

#Results: there are no duplicated rows

Duplicate Rows:
Empty GeoDataFrame
Columns: [id, @id, alt_name, amenity, architect, architect:wikidata, architect:wikipedia, artist:wikidata, artist:wikipedia, artist_name, artwork_type, barrier, covered, description, drinking_water, ele, fence_type, fountain, gnis:feature_id, height, historic, image, indoor, intermittent, level, lit, loc_name, material, memorial, name, name:fr, natural, official_name, operator, playground, source, start_date, subject, subject:wikidata, subject:wikipedia, tourism, url, water, website, website:alternate, wikidata, wikipedia, geometry]
Index: []

In [7]:
fountain_gdf.shape

(149, 48)

In [6]:
fountain_gdf.isnull().sum()

id                       0
@id                      0
alt_name               148
amenity                  0
architect              148
architect:wikidata     148
architect:wikipedia    148
artist:wikidata        148
artist:wikipedia       148
artist_name            147
artwork_type           147
barrier                111
covered                146
description            148
drinking_water         114
ele                    148
fence_type             148
fountain               115
gnis:feature_id        148
height                 143
historic               148
image                  147
indoor                 146
intermittent           148
level                  145
lit                    125
loc_name               148
material               148
memorial               148
name                   124
name:fr                148
natural                 70
official_name          148
operator               148
playground             148
source                 147
start_date             145
subject                148
subject:wikidata       148
subject:wikipedia      148
tourism                147
url                    147
water                  144
website                140
website:alternate      142
wikidata               139
wikipedia              142
geometry                 0
dtype: int64

In [8]:
fountain_gdf=fountain_gdf[['id','geometry']]

In [11]:
fountain_gdf=fountain_gdf.rename(columns={'id':'fountain_id'})

In [12]:
fountain_gdf

          fountain_id                                           geometry
0       way/260910558  POLYGON ((-73.97939 40.76179, -73.97943 40.761...
1       way/260910559  POLYGON ((-73.97966 40.76141, -73.97970 40.761...
2       way/262576692  POLYGON ((-73.98771 40.76260, -73.98773 40.762...
3       way/329988120  POLYGON ((-73.98336 40.77231, -73.98336 40.772...
4       way/371854423  POLYGON ((-74.00988 40.70265, -74.00989 40.702...
..                ...                                                ...
144  node/11656237160                         POINT (-73.95207 40.76660)
145  node/11656257170                         POINT (-73.95141 40.76630)
146  node/11768058262                         POINT (-73.96133 40.80314)
147  node/11817550746                         POINT (-73.96821 40.80176)
148  node/11966093623                         POINT (-73.95938 40.81793)

[149 rows x 2 columns]

In [13]:
fountain_gdf['fountain_id']=fountain_gdf.index+1

In [14]:
fountain_gdf

     fountain_id                                           geometry
0              1  POLYGON ((-73.97939 40.76179, -73.97943 40.761...
1              2  POLYGON ((-73.97966 40.76141, -73.97970 40.761...
2              3  POLYGON ((-73.98771 40.76260, -73.98773 40.762...
3              4  POLYGON ((-73.98336 40.77231, -73.98336 40.772...
4              5  POLYGON ((-74.00988 40.70265, -74.00989 40.702...
..           ...                                                ...
144          145                         POINT (-73.95207 40.76660)
145          146                         POINT (-73.95141 40.76630)
146          147                         POINT (-73.96133 40.80314)
147          148                         POINT (-73.96821 40.80176)
148          149                         POINT (-73.95938 40.81793)

[149 rows x 2 columns]

In [15]:
fountain_gdf.to_file('fountain_cleaned.geojson')