In [1]:
import pandas as pd
import geopandas as gpd
import matplotlib.pyplot as plt
from shapely.geometry import Point

In [2]:
toiletsOSM_gdf = gpd.read_file("toilet_OSM.geojson")

In [3]:
pd.set_option('display.max_columns', None)
#display all columns not truncated

In [4]:
toiletsOSM_gdf

,id,@id,access,addr:city,addr:housenumber,addr:place,addr:postcode,addr:state,addr:street,amenity,architect,building,building:colour,building:levels,building:material,changing_table,changing_table:location,charge,check_date,check_date:opening_hours,created_by,description,drinking_water,ele,fee,female,female:signed,fixme,gender_segregated,height,image,image:0,image:1,image:2,image:3,image:4,image:5,indoor,layer,level,male,male:signed,mapillary,name,note,nycdoitt:bin,opening_hours,opening_hours:signed,operator,portable,seasonal,source,source_ref,toilets:disposal,toilets:handwashing,toilets:paper_supplied,toilets:position,toilets:unisex,toilets:wheelchair,unisex,website,wheelchair,wikimedia_commons,geometry
0,way/160062003,way/160062003,yes,None,None,None,None,None,None,toilets,None,yes,None,None,None,None,None,None,2023-12-16,None,None,There are two entrances. The front entrance is...,None,None,no,yes,None,None,None,None,None,None,None,None,None,None,None,None,None,None,None,None,None,None,None,None,None,None,None,None,None,None,None,flush,None,None,None,None,None,None,None,None,None,"POLYGON ((-73.94618 40.84715, -73.94617 40.847..."
1,way/238356504,way/238356504,None,None,None,None,None,None,None,toilets,None,yes,None,None,None,None,None,None,None,None,None,None,None,None,None,None,None,None,None,None,None,None,None,None,None,None,None,None,None,None,None,None,None,None,None,None,None,None,None,None,None,None,None,None,None,None,None,None,None,None,None,None,None,"POLYGON ((-73.95904 40.75327, -73.95908 40.753..."
2,way/248166302,way/248166302,yes,None,200,Washington Square Park,None,None,None,toilets,None,yes,None,None,None,None,None,None,2024-06-09,None,None,None,None,None,no,None,None,None,None,4.6,None,None,None,None,None,None,None,None,None,None,None,None,None,Washington Square Park House,None,1088398,07:00-17:00,None,None,None,None,None,None,None,None,None,None,None,None,None,None,yes,None,"POLYGON ((-73.99834 40.73073, -73.99829 40.730..."
3,way/248266458,way/248266458,None,None,None,None,None,None,None,toilets,None,yes,None,None,None,None,None,None,None,None,None,None,None,None,None,None,None,None,None,3.2,None,None,None,None,None,None,None,None,None,None,None,None,None,None,None,1088212,None,None,None,None,None,None,None,None,None,None,None,None,None,None,None,None,None,"POLYGON ((-73.98561 40.72422, -73.98557 40.724..."
4,way/248773597,way/248773597,yes,None,None,None,None,None,None,toilets,None,yes,None,None,None,None,None,None,2024-01-18,None,None,None,None,None,no,None,None,None,None,3.3,None,None,None,None,None,None,None,None,None,0,None,None,None,None,None,1000000,08:00-16:00,None,None,no,None,survey,None,flush,yes,None,seated;urinal,None,None,yes,None,yes,None,"POLYGON ((-73.98951 40.73632, -73.98959 40.736..."
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
179,node/11870739703,node/11870739703,permissive,None,None,None,None,None,None,toilets,None,None,None,None,None,yes,None,None,None,None,None,None,None,None,None,None,None,None,None,None,None,None,None,None,None,None,None,None,None,None,yes,None,None,None,None,None,None,None,None,None,None,None,None,flush,None,None,None,None,None,None,None,yes,None,POINT (-74.00524 40.72683)
180,node/11870739704,node/11870739704,permissive,None,None,None,None,None,None,toilets,None,None,None,None,None,None,None,None,None,None,None,None,None,None,None,yes,None,None,None,None,None,None,None,None,None,None,None,None,None,None,None,None,None,None,None,None,None,None,None,None,None,None,None,flush,None,None,None,None,None,None,None,yes,None,POINT (-74.00524 40.72687)
181,node/11955796822,node/11955796822,yes,None,None,None,None,None,None,toilets,None,None,None,None,None,no,None,None,None,None,None,Seasonal. Only here in warmer months at whim ...,None,None,None,None,None,None,None,None,None,None,None,None,None,None,None,None,None,None,None,None,862363075930004,None,None,None,None,None,None,None,None,None,None,chemical,None,None,None,None,None,None,None,None,None,POINT (-73.95983 40.82028)
182,node/11955796823,node/11955796823,yes,None,None,None,None,None,None,toilets,None,None,None,None,None,no,None,None,None,None,None,Seasonal. Only here in warmer months at whim ...,None,None,None,None,None,None,None,None,None,None,None,None,None,None,None,None,None,None,None,None,862363075930004,None,None,None,None,None,None,None,None,None,None,chemical,None,None,None,None,None,None,None,None,None,POINT (-73.95982 40.82029)
183,node/11971148597,node/11971148597,yes,None,None,None,None,None,None,toilets,None,None,None,None,None,None,None,None,2024-06-10,None,None,None,None,None,no,None,None,location,None,None,None,None,None,None,None,None,None,None,None,1,None,None,None,None,None,None,None,None,None,None,None,None,None,None,None,None,None,None,None,None,None,yes,None,POINT (-73.99131 40.75708)

In [5]:
toiletsOSM_gdf.columns

Index(['id', '@id', 'access', 'addr:city', 'addr:housenumber', 'addr:place',
       'addr:postcode', 'addr:state', 'addr:street', 'amenity', 'architect',
       'building', 'building:colour', 'building:levels', 'building:material',
       'changing_table', 'changing_table:location', 'charge', 'check_date',
       'check_date:opening_hours', 'created_by', 'description',
       'drinking_water', 'ele', 'fee', 'female', 'female:signed', 'fixme',
       'gender_segregated', 'height', 'image', 'image:0', 'image:1', 'image:2',
       'image:3', 'image:4', 'image:5', 'indoor', 'layer', 'level', 'male',
       'male:signed', 'mapillary', 'name', 'note', 'nycdoitt:bin',
       'opening_hours', 'opening_hours:signed', 'operator', 'portable',
       'seasonal', 'source', 'source_ref', 'toilets:disposal',
       'toilets:handwashing', 'toilets:paper_supplied', 'toilets:position',
       'toilets:unisex', 'toilets:wheelchair', 'unisex', 'website',
       'wheelchair', 'wikimedia_commons', 'geometry'],
      dtype='object')

In [6]:
toiletsOSM_gdf.head()

,id,@id,access,addr:city,addr:housenumber,addr:place,addr:postcode,addr:state,addr:street,amenity,architect,building,building:colour,building:levels,building:material,changing_table,changing_table:location,charge,check_date,check_date:opening_hours,created_by,description,drinking_water,ele,fee,female,female:signed,fixme,gender_segregated,height,image,image:0,image:1,image:2,image:3,image:4,image:5,indoor,layer,level,male,male:signed,mapillary,name,note,nycdoitt:bin,opening_hours,opening_hours:signed,operator,portable,seasonal,source,source_ref,toilets:disposal,toilets:handwashing,toilets:paper_supplied,toilets:position,toilets:unisex,toilets:wheelchair,unisex,website,wheelchair,wikimedia_commons,geometry
0,way/160062003,way/160062003,yes,None,None,None,None,None,None,toilets,None,yes,None,None,None,None,None,None,2023-12-16,None,None,There are two entrances. The front entrance is...,None,None,no,yes,None,None,None,None,None,None,None,None,None,None,None,None,None,None,None,None,None,None,None,None,None,None,None,None,None,None,None,flush,None,None,None,None,None,None,None,None,None,"POLYGON ((-73.94618 40.84715, -73.94617 40.847..."
1,way/238356504,way/238356504,None,None,None,None,None,None,None,toilets,None,yes,None,None,None,None,None,None,None,None,None,None,None,None,None,None,None,None,None,None,None,None,None,None,None,None,None,None,None,None,None,None,None,None,None,None,None,None,None,None,None,None,None,None,None,None,None,None,None,None,None,None,None,"POLYGON ((-73.95904 40.75327, -73.95908 40.753..."
2,way/248166302,way/248166302,yes,None,200,Washington Square Park,None,None,None,toilets,None,yes,None,None,None,None,None,None,2024-06-09,None,None,None,None,None,no,None,None,None,None,4.6,None,None,None,None,None,None,None,None,None,None,None,None,None,Washington Square Park House,None,1088398,07:00-17:00,None,None,None,None,None,None,None,None,None,None,None,None,None,None,yes,None,"POLYGON ((-73.99834 40.73073, -73.99829 40.730..."
3,way/248266458,way/248266458,None,None,None,None,None,None,None,toilets,None,yes,None,None,None,None,None,None,None,None,None,None,None,None,None,None,None,None,None,3.2,None,None,None,None,None,None,None,None,None,None,None,None,None,None,None,1088212,None,None,None,None,None,None,None,None,None,None,None,None,None,None,None,None,None,"POLYGON ((-73.98561 40.72422, -73.98557 40.724..."
4,way/248773597,way/248773597,yes,None,None,None,None,None,None,toilets,None,yes,None,None,None,None,None,None,2024-01-18,None,None,None,None,None,no,None,None,None,None,3.3,None,None,None,None,None,None,None,None,None,0,None,None,None,None,None,1000000,08:00-16:00,None,None,no,None,survey,None,flush,yes,None,seated;urinal,None,None,yes,None,yes,None,"POLYGON ((-73.98951 40.73632, -73.98959 40.736..."

In [7]:
toiletsOSM_gdf['name'].value_counts()

name
Washington Square Park House            1
Pier 45 Comfort Station                 1
Payson Nature Center                    1
Octagon Comfort Station                 1
High Bridge Recreation Center           1
Famous Famiglia                         1
Tavern on the Green public restrooms    1
Bryant Park public toilets              1
Chelsea Park Toilets                    1
Name: count, dtype: int64

In [8]:
toiletsOSM_gdf.shape

(184, 64)

In [9]:
toiletsOSM_gdf['access'].value_counts()

access
yes           68
permissive     5
customers      3
no             1
Name: count, dtype: int64

In [10]:
toiletsOSM_gdf.isnull().sum()

id                     0
@id                    0
access               107
addr:city            183
addr:housenumber     175
                    ...
unisex               170
website              181
wheelchair           121
wikimedia_commons    181
geometry               0
Length: 64, dtype: int64

In [11]:
toiletsOSM_gdf['addr:place'].isnull().sum()

183

In [12]:
toiletsOSM_gdf=toiletsOSM_gdf[['id','name', 'geometry']]

In [13]:
toiletsOSM_gdf

,id,name,geometry
0,way/160062003,None,"POLYGON ((-73.94618 40.84715, -73.94617 40.847..."
1,way/238356504,None,"POLYGON ((-73.95904 40.75327, -73.95908 40.753..."
2,way/248166302,Washington Square Park House,"POLYGON ((-73.99834 40.73073, -73.99829 40.730..."
3,way/248266458,None,"POLYGON ((-73.98561 40.72422, -73.98557 40.724..."
4,way/248773597,None,"POLYGON ((-73.98951 40.73632, -73.98959 40.736..."
...,...,...,...
179,node/11870739703,None,POINT (-74.00524 40.72683)
180,node/11870739704,None,POINT (-74.00524 40.72687)
181,node/11955796822,None,POINT (-73.95983 40.82028)
182,node/11955796823,None,POINT (-73.95982 40.82029)
183,node/11971148597,None,POINT (-73.99131 40.75708)

In [19]:
toiletsOSM_gdf

,name,geometry
0,None,"POLYGON ((-73.94618 40.84715, -73.94617 40.847..."
1,None,"POLYGON ((-73.95904 40.75327, -73.95908 40.753..."
2,Washington Square Park House,"POLYGON ((-73.99834 40.73073, -73.99829 40.730..."
3,None,"POLYGON ((-73.98561 40.72422, -73.98557 40.724..."
4,None,"POLYGON ((-73.98951 40.73632, -73.98959 40.736..."
...,...,...
179,None,POINT (-74.00524 40.72683)
180,None,POINT (-74.00524 40.72687)
181,None,POINT (-73.95983 40.82028)
182,None,POINT (-73.95982 40.82029)
183,None,POINT (-73.99131 40.75708)

In [16]:
toiletsOSM_gdf

,name,geometry
0,None,"POLYGON ((-73.94618 40.84715, -73.94617 40.847..."
1,None,"POLYGON ((-73.95904 40.75327, -73.95908 40.753..."
2,Washington Square Park House,"POLYGON ((-73.99834 40.73073, -73.99829 40.730..."
3,None,"POLYGON ((-73.98561 40.72422, -73.98557 40.724..."
4,None,"POLYGON ((-73.98951 40.73632, -73.98959 40.736..."
...,...,...
179,None,POINT (-74.00524 40.72683)
180,None,POINT (-74.00524 40.72687)
181,None,POINT (-73.95983 40.82028)
182,None,POINT (-73.95982 40.82029)
183,None,POINT (-73.99131 40.75708)

In [17]:
#toiletsOSM_gdf.to_file('toiletsOSM_cleaned.geojson',driver='GeoJSON')

In [18]:
toiletsOSM_gdf.crs

<Geographic 2D CRS: EPSG:4326>
Name: WGS 84
Axis Info [ellipsoidal]:
- Lat[north]: Geodetic latitude (degree)
- Lon[east]: Geodetic longitude (degree)
Area of Use:
- undefined
Datum: World Geodetic System 1984
- Ellipsoid: WGS 84
- Prime Meridian: Greenwich